source:
  type: hackernews
  args: {}  # No additional args needed

transformers:
  - type: content_fetcher
    args: {}
  - type: summarizer
    args: {}
  - type: comment_summarizer
    args: {}
  - type: content_tagger
    args: {}

formatter:
  type: markdown  # Markdown works better with Telegram
  args:
    template_path: templates/markdown/article.md

destination:
  type: telegram
  args:
    bot_token: ${TELEGRAM_BOT_TOKEN}
    chat_id: ${TELEGRAM_CHAT_ID}
